[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bunkalunk"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
  "fitdecode",
  "h5py",
  "requests"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["bunkalunk*"]

[tool.mypy]
# Look in the 'typings' folder for library stubs
# mypy_path = "./typings"

# Optional: ensure mypy is strict about imports
disallow_untyped_calls = true
namespace_packages = true
explicit_package_bases = true

[tool.pyright]
stubPath = "typings"
